/**
 * Style Dictionary v4 Configuration
 * Generates typed tokens & CSS custom properties for @inq/tokens
 */

export default {
  source: ['src/tokens/**/*.json'],
  hooks: {
    formats: {
      'css/themed-variables': ({ dictionary }) => {
        const rootTokens = [];
        const lightTokens = [];
        const darkTokens = [];

        for (const token of dictionary.allTokens) {
          const path = token.path;
          if (path[0] === 'color' && path[1] === 'light') {
            const varName = path.slice(2).join('-');
            lightTokens.push(`  --${varName}: ${token.value};`);
          } else if (path[0] === 'color' && path[1] === 'dark') {
            const varName = path.slice(2).join('-');
            darkTokens.push(`  --${varName}: ${token.value};`);
          } else {
            rootTokens.push(`  --${token.name}: ${token.value};`);
          }
        }

        return `/**
 * Do not edit directly. Auto-generated by Style Dictionary v4.
 * @inq/tokens - Design Tokens CSS Variables
 */

:root {
${rootTokens.join('\n')}

  /* Semantic Aliases */
  --color-primary: var(--color-brand-primary);
  --color-primary-hover: var(--color-brand-primary-hover);
  --color-primary-light: var(--color-brand-primary-light);
  --color-primary-subtle: var(--color-brand-primary-subtle);

  --color-danger: var(--color-brand-coral);
  --color-danger-hover: var(--color-brand-coral-hover);
  --color-danger-light: var(--color-brand-coral-light);

  --color-warning: var(--color-brand-amber);
  --color-warning-hover: var(--color-brand-amber-hover);
  --color-warning-light: var(--color-brand-amber-light);

  --color-success: var(--color-brand-emerald);
  --color-success-hover: var(--color-brand-emerald-hover);
  --color-success-light: var(--color-brand-emerald-light);

  --color-info: var(--color-brand-primary);

  /* Transition timings */
  --transition-fast: 150ms cubic-bezier(0.4, 0, 0.2, 1);
  --transition-normal: 250ms cubic-bezier(0.4, 0, 0.2, 1);
  --transition-spring: 300ms cubic-bezier(0.34, 1.56, 0.64, 1);
}

/* Light Theme (Clean High-End Surface) */
:root,
[data-theme="light"] {
${lightTokens.join('\n')}
  --border-focus: var(--color-brand-primary);
  --toolbar-bg: rgba(255, 255, 255, 0.92);
  --toolbar-border: rgba(224, 226, 230, 0.85);
  --toolbar-shadow: 0 8px 32px rgba(0, 0, 0, 0.08);
}

/* Dark Theme (Deep Refined Surface) */
[data-theme="dark"] {
${darkTokens.join('\n')}
  --border-focus: #8ab4f8;
  --toolbar-bg: rgba(30, 31, 32, 0.88);
  --toolbar-border: rgba(68, 71, 70, 0.6);
  --toolbar-shadow: 0 8px 32px rgba(0, 0, 0, 0.35);
}
`;
      },

      'javascript/tree-shakeable': ({ dictionary }) => {
        const brand = {};
        const semantic = {};
        const light = { surface: {}, text: {}, border: {} };
        const dark = { surface: {}, text: {}, border: {} };
        const typo = { fontFamily: {}, fontSize: {}, fontWeight: {}, lineHeight: {} };
        const space = {};
        const radius = {};
        const elev = { shadow: {}, backdropBlur: {} };

        for (const token of dictionary.allTokens) {
          const path = token.path;
          if (path[0] === 'color') {
            if (path[1] === 'brand') brand[path[2]] = token.value;
            else if (path[1] === 'semantic') semantic[path[2]] = token.value;
            else if (path[1] === 'light') light[path[2]][path[3]] = token.value;
            else if (path[1] === 'dark') dark[path[2]][path[3]] = token.value;
          } else if (path[0] === 'typography') {
            if (path[1] === 'fontFamily') typo.fontFamily[path[2]] = token.value;
            else if (path[1] === 'fontSize') typo.fontSize[path[2]] = token.value;
            else if (path[1] === 'fontWeight') typo.fontWeight[path[2]] = Number(token.value);
            else if (path[1] === 'lineHeight') typo.lineHeight[path[2]] = Number(token.value);
          } else if (path[0] === 'spacing') {
            space[path[1]] = token.value;
          } else if (path[0] === 'borderRadius') {
            radius[path[1]] = token.value;
          } else if (path[0] === 'elevation') {
            if (path[1] === 'shadow') elev.shadow[path[2]] = token.value;
            else if (path[1] === 'backdropBlur') elev.backdropBlur[path[2]] = token.value;
          }
        }

        return `/**
 * Do not edit directly. Auto-generated by Style Dictionary v4.
 * @inq/tokens - Tree-Shakeable Design Tokens
 */

export const brandColors = ${JSON.stringify(brand, null, 2)};
export const semanticColors = ${JSON.stringify(semantic, null, 2)};
export const lightTheme = ${JSON.stringify(light, null, 2)};
export const darkTheme = ${JSON.stringify(dark, null, 2)};
export const typography = ${JSON.stringify(typo, null, 2)};
export const spacing = ${JSON.stringify(space, null, 2)};
export const radii = ${JSON.stringify(radius, null, 2)};
export const elevation = ${JSON.stringify(elev, null, 2)};
export const transitions = {
  fast: "150ms cubic-bezier(0.4, 0, 0.2, 1)",
  normal: "250ms cubic-bezier(0.4, 0, 0.2, 1)",
  spring: "300ms cubic-bezier(0.34, 1.56, 0.64, 1)"
};
`;
      },

      'typescript/tree-shakeable-declarations': ({ dictionary }) => {
        return `/**
 * Do not edit directly. Auto-generated by Style Dictionary v4.
 * @inq/tokens - TypeScript Definitions
 */

export declare const brandColors: {
  readonly primary: string;
  readonly primaryHover: string;
  readonly primaryLight: string;
  readonly primarySubtle: string;
  readonly coral: string;
  readonly coralHover: string;
  readonly coralLight: string;
  readonly amber: string;
  readonly amberHover: string;
  readonly amberLight: string;
  readonly emerald: string;
  readonly emeraldHover: string;
  readonly emeraldLight: string;
};

export declare const semanticColors: {
  readonly primary: string;
  readonly danger: string;
  readonly warning: string;
  readonly success: string;
  readonly info: string;
};

export declare const lightTheme: {
  readonly surface: {
    readonly canvas: string;
    readonly card: string;
    readonly elevated: string;
    readonly hover: string;
    readonly active: string;
  };
  readonly text: {
    readonly primary: string;
    readonly secondary: string;
    readonly muted: string;
    readonly inverse: string;
  };
  readonly border: {
    readonly subtle: string;
    readonly default: string;
    readonly focus: string;
  };
};

export declare const darkTheme: typeof lightTheme;

export declare const typography: {
  readonly fontFamily: {
    readonly sans: string;
    readonly mono: string;
  };
  readonly fontSize: Record<string, string>;
  readonly fontWeight: Record<string, number>;
  readonly lineHeight: Record<string, number>;
};

export declare const spacing: Record<string, string>;
export declare const radii: Record<string, string>;
export declare const elevation: {
  readonly shadow: Record<string, string>;
  readonly backdropBlur: Record<string, string>;
};

export declare const transitions: {
  readonly fast: string;
  readonly normal: string;
  readonly spring: string;
};

export type BrandColors = typeof brandColors;
export type SemanticColors = typeof semanticColors;
export type LightTheme = typeof lightTheme;
export type DarkTheme = typeof darkTheme;
export type Typography = typeof typography;
export type Spacing = typeof spacing;
export type Radii = typeof radii;
export type Elevation = typeof elevation;
export type Transitions = typeof transitions;
`;
      }
    }
  },
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/themed-variables'
        }
      ]
    },
    js: {
      transformGroup: 'js',
      buildPath: 'dist/',
      files: [
        {
          destination: 'tokens.js',
          format: 'javascript/tree-shakeable'
        },
        {
          destination: 'tokens.d.ts',
          format: 'typescript/tree-shakeable-declarations'
        }
      ]
    }
  }
};
